### ISSUE TITLE
Support decimal type

### ISSUE THREAD

**Issue by xotahal** [SphtKr/JSONAPI.NET#29]
Hello,

my model has `decimal` type and it isn't write as primitive type in JSON output. I was looking to code and there is method called `CanWriteTypeAsPrimitive` which returns false for `decimal`. Is it ok? It behaves similiar for `Nullable<int>`, `Nullable<decimal>`, etc.

**Comment by SphtKr** [comment]
Thanks for bringing this to our attention. Yes, that's the first place that will need a change, at least. The corresponding test in JSONAPI.Tests should also be updated. Then we'll have to see if the formatter will already handle `Decimal` or needs extra code to format it...hopefully not and it will just work. If you'd like to submit a pull request, please do!

I'm going to call this a bug as it's a bit of an obvious oversight. We can probably roll this and one other already done bugfix into a 0.2.2 release.

**Comment by SphtKr** [comment]
I created a branch for 0.2.2 bugfixes, so if you fork and do a PR, try to make the changes on that branch, or a new branch from this commit: https://github.com/SphtKr/JSONAPI.NET/commit/9259ae9f392ec4b68e2fadd6112dea6ebd24e784

**Comment by SphtKr** [comment]
One more question, sorry...thinking about this, `Decimal` should probably be serialized to a string in the JSON, not a number (since serializing it to a JSON number could lose precision, and that's the point of `Decimal`). Is that what you would expect also?

**Comment by SphtKr** [comment]
Reopening so we can try and backport this to 0.2.2 (the milestone originally assigned)

**Comment by xotahal** [comment]
> One more question, sorry...thinking about this, Decimal should probably be serialized to a string in the JSON, not a number (since serializing it to a JSON number could lose precision, and that's the point of Decimal). Is that what you would expect also?

Yes that's true. But I would like to serialize Decimal as number sometimes. There could be attribute:

`[SerializeValueAs(SerializeValueAsOption.Number)]`

What do you mean?

**Comment by SphtKr** [comment]
Yes, we've thought about exactly that kind of attribute solution.

@csantero has implemented string serialization of `Decimal` in master, which will become 0.3.0 soon, but we don't have the attribute to change serialization to a number yet. Something like that will probably wait for 0.4.0 at least, as we're trying to get 0.3.0 out. In the meantime, I *think* you could use a `IContractResolver` to change the serialization behavior.

**Comment by csantero** [comment]
I merged this fix back into the 0.2.2 branch. @SphtKr are you still planning to make a 0.2.2 release?
