### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by karlguillotte** [SphtKr/JSONAPI.NET#42]
First, thanks for sharing your work. 

I have been looking at all the commits since last deployment on Nuget and I was wondering if you are planning another release soon. There are lots of new features and fixes that I would like to give them a try. 

You have one bug remaining for milestone 0.2.2 (decimal) and it is actually something I would need. 

Thanks!

**Comment by csantero** [comment]
@karlguillotte I am actually finishing up a PR as we speak that handles decimals and nullable primitive types.

Hopefully we can get a new release out this week. @SphtKr I think we can skip 0.2.2 and just release 0.3.0 if you're okay with that?

**Comment by karlguillotte** [comment]
That is good news. Thanks @csantero  

Ah! I am having an issue with null int. It will probably be solved with your PR ;) I will give a try once a new release will be available. 

Thanks for the hard work.

**Comment by SphtKr** [comment]
Yes I think we can wrap up a few of the in-progress changes and push a 0.3 in a few days. Be advised, there are significant changes to the API in what will be 0.3! This will probably be the case for 0.4 as well, as we're trying to hash out some significant refactors. This is to be expected this early but I know it can be irritating. 

I might backport the decimal fix and push it to a 0.2.2 release as well (though this doesn't *have* to happen before 0.3 is released). I thought it would be nice to get that and #6 to anyone who doesn't have time to integrate the latest changes...I remember feeling burned a lot in earlier versions of Ember Data when this happened.

**Comment by SphtKr** [comment]
Also, if you'd like to try prerelease builds, I think you can get the automatically built CI Nuget packages here: https://www.myget.org/feed/Packages/jsonapi

**Comment by karlguillotte** [comment]
Thanks for the link. I think I will wait for the next release. I am a real newbie with those technologies. 

Thanks for the note with the breaking changes. I am starting a new web api, so not much code yet.

**Comment by karlguillotte** [comment]
Hi @SphtKr ,

I tried to go on the MyGet and I do not see the package. Is it public?

Thanks!

**Comment by SphtKr** [comment]
@karlguillote Hmm... Well it's not private or if be paying for it by now. Sorry I haven't gotten the package finalized yet. What I did do for you is push a pre-release version of 0.3.0 to NuGet. You can find that here: https://www.nuget.org/packages/JSONAPI/0.3.0-pre-1 , and https://www.nuget.org/packages/JSONAPI.EntityFramework/0.3.0-pre-1 .

Since, as I said, the docs aren't where they need to be, please ask any questions you want--throw them up on StackOverflow so we'll start building a knowledge base there. I think if you @mention my username there I'll get notified. Or drop a link to the question here.

**Comment by karlguillotte** [comment]
Thanks @SphtKr  and @csantero for your hard work. I installed them. 

I am having an issue, I will post on StackOverflow.
