### ISSUE TITLE
Controller endpoint naming/URL building convention

### ISSUE THREAD

**Issue by SphtKr** [SphtKr/JSONAPI.NET#55]
Apparently I had been using a rather outdated [JsonApiAdapter](/kurko/ember-json-api). When I updated to the latest, I noticed that by default it produces controller URLs in snake_case. (Is this the WebAPI default? Or used to be? Somehow mine have no underscores and I don't see where I've customized that if I have.)

Possibly in contrast, json-api/json-api#341 indirectly recommends dasherized names: 

> Dasherized and pluralized resource types can be used as URL segments without translation, as discussed below.

(Though strictly speaking the spec remains agnostic to URL conventions.) This also seems to be a REST best practice, perhaps.

Either can be supported via a `IHttpControllerSelector`, and it can be made to even support multiple paths for a single controller. Should we add an `IHttpControllerSelector` to JSONAPI.NET to support dasherized paths?

**Comment by csantero** [comment]
I have an `IHttpControllerSelector` in my project that dasherizes controller names (web api uses camel case by default). I can bring that over.

**Comment by csantero** [comment]
This is implemented in the 0-4-0 branch.
