### ISSUE TITLE
RC2: Include resource type name in resource

### ISSUE THREAD

**Issue by csantero** [SphtKr/JSONAPI.NET#59]
https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#resource-objects-

> A resource object MUST contain at least the following top-level members:

> "id"
> "type"

I hate the naming for this - my project has a bunch of models that have a property called Type. But I haven't seen anyone complain about it, so I guess I'm the one who has to change.

We do have to handle the possibility that someone's model has a property that would serialize as `type`, though. Either we can throw an exception, or we can transform the name somehow (like prepending an underscore).

**Comment by karlguillotte** [comment]
Actually, I would like to have this feature added, I need it on the client side ;) Not sure why they decided to pluralize it.

**Comment by SphtKr** [comment]
Ditto, I'm looking forward to being able to tell the difference. I've started experimenting with a polymorphic endpoint and so far JSONAPI.NET seems to handle them okay, for GET at least. Was worried about that...fingers crossed.

**Comment by csantero** [comment]
Implemented in #80. Will track reserved attribute name collisions in another issue.
