### ISSUE TITLE
Only top-level errors get IDs 

### ISSUE THREAD

**Issue by SphtKr** [SphtKr/JSONAPI.NET#63]
see http://stackoverflow.com/questions/28507365/can-not-query-a-single-resource-after-upgrading-jsonapi-net-to-latest-version-0 , the stack trace shows null for all IDs except the first/top. Spec doesn't say anything about subobjects having IDs, but it looks kind of odd for them to have an id field that's null. Is this easily fixable or do we care?

**Comment by csantero** [comment]
I can fix that.
